### ISSUE TITLE
Windows: Error when editing HTML files in Atom

### ISSUE THREAD

**Issue by gemmaweirs** [paulhorner79/atom-lipsum#2]
Error: 'node' is not recognized as an internal or external command, operable program or batch file.
Error: 'node' is not recognized as an internal or external command,
operable program or batch file.
    at ChildProcess.<anonymous> (C:\Users\gemma\.atom\packages\linter-bootlint\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by paulhorner79** [comment]
It looks like the issue being reported is from the linter-bootlint package rather than the lipsum package (it's a known issue with that package - https://github.com/AtomLinter/linter-bootlint/issues/92 - you will need to install node.js locally for that package to work without throwing this error).  

If this is being reported by your system as an issue with the lipsum package could you try disabling linter-bootlint and let me know if the issue is still being reported?

**Comment by gemmaweirs** [comment]
Oops! My bad... I must have been tired and distracted cos it looks like I posted this for the wrong package. My apologies. :/ But thanks for the heads-up. I'll install node.js and see if that resolves the issue. :)
